apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudstorage
  labels:
    region: ${region}
    zone: ${dc}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ibmc-file-gold-gid